name: ZettlrIOS
options:
  bundleIdPrefix: com.apple.development
  deploymentTarget:
    iOS: 15.0
packages:
  Down:
    url: https://github.com/johnxnguyen/Down.git
    from: 0.11.0
  SwiftyJSON:
    url: https://github.com/SwiftyJSON/SwiftyJSON.git
    from: 5.0.0
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: 5.0.0
targets:
  ZettlrIOS:
    type: application
    platform: iOS
    sources: [ZettlrIOS]
    dependencies:
      - package: Down
      - package: SwiftyJSON
      - package: Yams
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.apple.development.zettlrios
        DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    info:
      path: ZettlrIOS/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: Zettlr
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIBackgroundModes:
          - fetch
          - remote-notification
        NSUbiquitousContainers:
          iCloud.com.example.zettlr:
            NSUbiquitousContainerIsDocumentScopePublic: true
            NSUbiquitousContainerName: Zettlr
            NSUbiquitousContainerSupportedFolderLevels: Any
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: ZettlrIOS/ZettlrIOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.example.zettlr
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.example.zettlr
